1 – Crie dois dataFrames (Tabelas):
•O Primeiro: Filtre na coluna “grape_type” somente os valores “Wine”, filtre na coluna “location_type” o valor “Brazil_State” e por fim, a coluna “category” o valor “Sales”;
•O Segundo: Filtre na coluna “grape_type” somente os valores “Table” e a coluna “category” o valor “Sales”.
No fim, use describe().T, qual das duas possuí a maior média na coluna “value_usd”?

In [2]:
import pandas as pd


df01 =pd.read_excel("vinhos_exercicio.xlsx")
df02 = pd.read_excel("vinhos_exercicio.xlsx")
dfOrigem=pd.read_excel("vinhos_exercicio.xlsx")

df01 = df01[
    (df01["grape_type"] == "Wine") &
    (df01["location_type"] == "Brazil_State") &
    (df01["category"] == "Sales")
]
print(df01)

df02 = df02[
    (df02["grape_type"]=="Table") &
    (df02["category"]=="Sales")
]
print(df02)

print(df01.describe().loc["mean"].T.compare(df02.describe().loc["mean"].T))

mediadf01=df01["value_usd"].mean()
mediadf02=df02["value_usd"].mean()
if mediadf01>mediadf02:
    print(f"A média do DF01: {mediadf01:.2f} é maior que do DF02: {mediadf02:.2f} e a diferença é de: {(mediadf01-mediadf02):.2f}")
else:
    print(f"A média do DF02: {mediadf02:.2f} é maior que do DF01: {mediadf01:.2f} e a diferença é de: {(mediadf02-mediadf01):.2f}")

    year grape_type location_type category  volume_hl  value_usd location
0   2018       Wine  Brazil_State    Sales       1200      50000       RS
1   2019       Wine  Brazil_State    Sales       1500      65000       SC
2   2020       Wine  Brazil_State    Sales       1100      48000       SP
3   2021       Wine  Brazil_State    Sales       1600      70000       RS
4   2022       Wine  Brazil_State    Sales       1700      72000       MG
20  2023       Wine  Brazil_State    Sales       1800      75000       RS
    year grape_type location_type category  volume_hl  value_usd location
10  2018      Table  Brazil_State    Sales       1300      40000       RS
11  2019      Table  Brazil_State    Sales       1400      42000       SC
12  2020      Table  Brazil_State    Sales       1500      45000       SP
13  2021      Table  Brazil_State    Sales       1600      47000       MG
14  2022      Table  Brazil_State    Sales       1700      49000       RS
21  2023      Table  Brazil_State    Sales       1800      50000       SC
                   self    other
volume_hl   1483.333333   1550.0
value_usd  63333.333333  45500.0
A média do DF01: 63333.33 é maior que do DF02: 45500.00 e a diferença é de: 17833.33

2 – Nestes dataFrames, ordene o ano de forma decrescente e o value_usd crescente. No fim, selecione as colunas year, grape_type, volume_hl, value_usd e location, nessa ordem. Use iloc[]

In [34]:
df01.sort_values(by="year", ascending=False, inplace=True)
df01.iloc[:,[0,1,4,5,6]]

    year grape_type  volume_hl  value_usd location
20  2023       Wine       1800      75000       RS
4   2022       Wine       1700      72000       MG
3   2021       Wine       1600      70000       RS
2   2020       Wine       1100      48000       SP
1   2019       Wine       1500      65000       SC
0   2018       Wine       1200      50000       RS

In [35]:
df02.iloc[:,[0,1,4,5,6]]
df02.sort_values(by="value_usd",ascending=True,inplace=False)

    year grape_type location_type category  volume_hl  value_usd location
10  2018      Table  Brazil_State    Sales       1300      40000       RS
11  2019      Table  Brazil_State    Sales       1400      42000       SC
12  2020      Table  Brazil_State    Sales       1500      45000       SP
13  2021      Table  Brazil_State    Sales       1600      47000       MG
14  2022      Table  Brazil_State    Sales       1700      49000       RS
21  2023      Table  Brazil_State    Sales       1800      50000       SC

3 – Usando o loc[], selecione as 10 primeiras linhas de cada dataFrame

In [42]:
df01.reset_index(drop=True,inplace=True)
df02.reset_index(drop=True,inplace=True)

print(df01.loc[0:10])
print("-"*50)
print(df02.loc[0:10])

   year grape_type location_type category  volume_hl  value_usd location
0  2023       Wine  Brazil_State    Sales       1800      75000       RS
1  2022       Wine  Brazil_State    Sales       1700      72000       MG
2  2021       Wine  Brazil_State    Sales       1600      70000       RS
3  2020       Wine  Brazil_State    Sales       1100      48000       SP
4  2019       Wine  Brazil_State    Sales       1500      65000       SC
5  2018       Wine  Brazil_State    Sales       1200      50000       RS
--------------------------------------------------
   year grape_type location_type category  volume_hl  value_usd location
0  2018      Table  Brazil_State    Sales       1300      40000       RS
1  2019      Table  Brazil_State    Sales       1400      42000       SC
2  2020      Table  Brazil_State    Sales       1500      45000       SP
3  2021      Table  Brazil_State    Sales       1600      47000       MG
4  2022      Table  Brazil_State    Sales       1700      49000       RS
5  2023      Table  Brazil_State    Sales       1800      50000       SC

4 – Faça uma análise do resultado alcançado e descreva ela no seu notebook. Analisando os dados,  responda:
Qual UF, possuí maior  “value_usd” para vinhos do tipo Wine na categoria “Sales”? Use o sort_by e o head(1) para mostrar o resultado.
Olhando para a base toda qual location possuí maior valor de importação? Use o sort_by e o head(1) para mostrar o resultado.
Olhando para a base toda qual location possuí maior valor de exportação? Use o sort_by e o head(1) para mostrar o resultado.
No fim comente sobre os resultados encontrados.

De acordo com as informações todos são do mesmo ano de 2023 e todos são do mesmo tipo de uva Vinho, e o de maior valor vem dos USA

In [ ]:
print(df01.sort_values(by="value_usd",ascending=False).head(1))
print("-"*50)

Import=dfOrigem[
    (dfOrigem["category"]=="Import")
]
print(Import.sort_values(by="value_usd",ascending=False).head(1))

print("-"*50)

Export=dfOrigem[
    (dfOrigem["category"]=="Export")
]
print(Export.sort_values(by="value_usd",ascending=False).head(1))

    year grape_type location_type category  volume_hl  value_usd location
20  2023       Wine  Brazil_State    Sales       1800      75000       RS
--------------------------------------------------
    year grape_type location_type category  volume_hl  value_usd location
22  2023       Wine       Country   Import       2300      99000    Chile
--------------------------------------------------
    year grape_type location_type category  volume_hl  value_usd location
23  2023       Wine       Country   Export       2400     102000      USA